version: "3"
services: 
  db:
    image: postgres
    env_file: 
      - .env
    ports: 
      - "5433:5432"
    volumes: 
      - ssedata:/var/lib/postgresql/data
  pgadmin:
    image: dockage/phppgadmin
    environment: 
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=mydb
    ports: 
      - "3001:80"

volumes: 
  ssedata: